services:
  - type: web
    name: sbgg
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1
    envVars:
      - key: RIOT_API_KEY
        sync: false
